version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@jscad/stl-serializer"
    versions:
    - 0.2.0
    - 2.0.0
    - 2.0.1
    - 2.0.2
  - dependency-name: typedoc
    versions:
    - 0.17.8
    - 0.20.28
    - 0.20.29
    - 0.20.30
    - 0.20.32
    - 0.20.33
    - 0.20.34
    - 0.20.35
  - dependency-name: "@types/marked"
    versions:
    - 1.2.1
    - 1.2.2
    - 2.0.0
    - 2.0.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: typescript-json-schema
    versions:
    - 0.48.0
    - 0.49.0
  - dependency-name: "@types/codemirror"
    versions:
    - 0.0.107
    - 0.0.108
